// <auto-generated />
namespace MyParking.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig001));
        
        string IMigrationMetadata.Id
        {
            get { return "201504282101504_mig001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
