// <auto-generated />
namespace MyParking.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MyParking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MyParking));
        
        string IMigrationMetadata.Id
        {
            get { return "201504081836028_MyParking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
